### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by andersonqi** [jesster2k10/rn-progress-hud#1]
I get this error with pod `The Swift pod rn-progress-hud depends upon SVProgressHUD, which does not define modules.`

**Comment by nagasai-tilicho** [comment]
### I got NullPointerException in `ANDROID`

## Error

> ### NullPointerException
> #### Attempt to invoke virtual method 'void android.view.ViewGroup.setBackgroundResource(int)' on a null object reference

## Stack trace

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setBackgroundResource(int)' on a null object reference
    at com.rnprogresshud.svprogresshud.SVProgressHUD.configMaskType(SVProgressHUD.java:258)
    at com.rnprogresshud.svprogresshud.SVProgressHUD.setMaskType(SVProgressHUD.java:240)
    at com.rnprogresshud.RnProgressHudModule$setMaskType$1.run(RnProgressHudModule.kt:75)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`
    

- [ ]  ##### **does anyone have any idea about this?**
